run:
  timeout: 5m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - unused
    - ineffassign
    - unused
    - gofmt
    - goimports
    - stylecheck

linters-settings:
  gofmt:
    simplify: true

  goimports:
    local-prefixes: "ewallet"

  stylecheck:
    checks:
      - all
      - 'ST1000' # Incorrect or missing package comment
      - 'ST1003' # Incorrectly capitalized identifier
      - 'ST1005' # Incorrectly formatted error strings

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-rules:
    - linters:
        - govet
      text: "unreachable code"

  include:
    - ".*\\.go$"
